### ISSUE TITLE
Не заходит на сервер

### ISSUE THREAD

**Issue by KoTuK606** [Elytrium/LimboAPI#133] opened 2024-01-13 14:54 UTC
**Ошибка**

```
[17:42:04 WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: net.elytrium.limboapi.injection.login.LoginListener$$Lambda/0x00007fbec0abeb98@3493f6d7
net.elytrium.commons.utils.reflection.ReflectionException: An unexpected internal error was caught during the reflection operations.
        at net.elytrium.limboapi.injection.login.LoginListener.lambda$hookLoginSession$2(LoginListener.java:225) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[server.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[server.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[server.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[server.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void com.velocitypowered.proxy.connection.MinecraftConnection.write(java.lang.Object)'
        at net.elytrium.limboapi.injection.login.LoginListener.lambda$hookLoginSession$2(LoginListener.java:165) ~[?:?]
        ... 8 more
```

**Сервер**

Velocity 3.3.0-SNAPSHOT (git-08c03aae-b320)
limboapi-1.1.18
limboauth-1.1.13
limbofilter-1.1.14
LuckPerms-Velocity-5.4.102
velocity-tools-1.2.0
FastMOTD-1.0.4
kaurivpn 1.9.2
skinsrestorer 15.0.3
geyser 2.2.0-SNAPSHOT
floodgate 2.2.2-SNAPSHOT

Ошибку пишет когда игрок пытается зайти на сервер (игрока сразу отключает (`[Netty epoll Worker #1/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]:  [initial connection] /айпиигрока has disconnected`))

**Comment by R00tB33rMan** [comment] 2024-01-13 19:23
This is a valid bug and is caused by LimboAPI. The latest iterations of Velocity incur this issue and they are not willing to make any changes for compatibility, sadly.

**Comment by EpicPlayerA10** [comment] 2024-01-13 22:44
Duplicate of #132

**Closed** 2024-01-14 00:18 UTC
Labels: bug
