### ISSUE TITLE
PacketEvents incompability

### ISSUE THREAD

**Issue by rafi67000** [Elytrium/LimboAPI#146] opened 2024-02-11 23:44 UTC
[Elytrium/FastPrepareAPI#3](https://github.com/Elytrium/FastPrepareAPI/issues/3)

**Comment by Emibergo02** [comment] 2024-04-01 21:48
bump

**Comment by UserNugget** [comment] 2024-05-22 19:51
> it's actually not fastPrepare issue but limboapi because it sends packet while user's state is still login???

LimboAPI sends some packets outside of FastPrepareAPI, making PacketEvents think that player is in login state.
Its most likely due to FastPrepareAPI sends already encoded packets (frame + compression + original packet), which PacketEvents doesnt support.

**Comment by UserNugget** [comment] 2024-05-22 20:17
~~Maybe~~ we can implement some kind of compatibility layer between FastPrepareAPI and PacketEvents, but it will limit some "functionality" of PacketEvents/FastPrepareAPI as them are incompatible by design.

**Comment by Brickgard** [comment] 2024-06-05 13:12
Passed through here with the same use-case issue/request.
Using PacketEvents to support SignedVelocity, and LimboAPI for LimboReconnect - would deeply appreciate any compatibility that could be explored for these features, thanks for the consideration and all your work!

**Comment by UserNugget** [comment] 2024-06-26 21:07
Oke, will try to fix this issue on PacketEvents side.

**Comment by TheFaik** [comment] 2024-07-04 14:26
Please solve this problem with PacketEvents, because the Pl-Hide-Pro plugin has become completely dependent on it.
The problem is the same - the player cannot enter the server and simply displays Time Out.

**Comment by bobhenl** [comment] 2024-07-04 14:32
I can confirm this is really issue, and big one when Pl-Hide-Pro requires PacketEvents

**Comment by TheFaik** [comment] 2024-07-05 14:14
Please Fix...

**Comment by TheFaik** [comment] 2024-07-09 14:51
Please Fix... 2x

**Comment by equqe** [comment] 2024-08-30 20:47
30/08 still an issue

**Comment by mdxd44** [comment] 2024-09-16 11:26
resolved in 6b3fb97a1e715bc4a0d3801399c1fae56eab895c

**Closed by mdxd44** 2024-09-16 11:26 UTC
Labels: bug
